name: Keep Render Apps Awake

on:
  schedule:
    # Run every 10 minutes (Render free tier sleeps after 15 mins)
    - cron: "*/10 * * * *"
  workflow_dispatch:  # allows manual run too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Old App
        run: curl -L https://assessment-rg57.onrender.com || true

      - name: Ping Backend
        run: curl -L https://server-form-webapp.onrender.com || true
